//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurrasDaTrinca.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChurrasDaTrinca.Language.ConfigurationResource", typeof(ConfigurationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Event/Add.
        /// </summary>
        public static string EventAdd {
            get {
                return ResourceManager.GetString("EventAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Event/ChangePastEventsValue.
        /// </summary>
        public static string EventChangePastEventsValue {
            get {
                return ResourceManager.GetString("EventChangePastEventsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Event/Delete.
        /// </summary>
        public static string EventDelete {
            get {
                return ResourceManager.GetString("EventDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Event/Details/.
        /// </summary>
        public static string EventDetails {
            get {
                return ResourceManager.GetString("EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Event/Edit/.
        /// </summary>
        public static string EventEdit {
            get {
                return ResourceManager.GetString("EventEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Event/List.
        /// </summary>
        public static string EventList {
            get {
                return ResourceManager.GetString("EventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Participant/Add.
        /// </summary>
        public static string ParticipantAdd {
            get {
                return ResourceManager.GetString("ParticipantAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Participant/Delete.
        /// </summary>
        public static string ParticipantDelete {
            get {
                return ResourceManager.GetString("ParticipantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Participant/Details/.
        /// </summary>
        public static string ParticipantDetails {
            get {
                return ResourceManager.GetString("ParticipantDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Participant/Edit/.
        /// </summary>
        public static string ParticipantEdit {
            get {
                return ResourceManager.GetString("ParticipantEdit", resourceCulture);
            }
        }
    }
}
