//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurrasDaTrinca.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChurrasDaTrinca.Language.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Evento.
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Participante.
        /// </summary>
        public static string AddParticipant {
            get {
                return ResourceManager.GetString("AddParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor já Pago:.
        /// </summary>
        public static string AmountAlreadyPaid {
            get {
                return ResourceManager.GetString("AmountAlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuição (R$).
        /// </summary>
        public static string Contribution {
            get {
                return ResourceManager.GetString("Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuição.
        /// </summary>
        public static string ContributionWithoutCurrency {
            get {
                return ResourceManager.GetString("ContributionWithoutCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebida.
        /// </summary>
        public static string Drink {
            get {
                return ResourceManager.GetString("Drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Evento.
        /// </summary>
        public static string EditEvent {
            get {
                return ResourceManager.GetString("EditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Participante.
        /// </summary>
        public static string EditParticipant {
            get {
                return ResourceManager.GetString("EditParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHURRAS DA TRINCA.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Bebuns:.
        /// </summary>
        public static string NumberDrunks {
            get {
                return ResourceManager.GetString("NumberDrunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Saudáveis:.
        /// </summary>
        public static string NumberHealthy {
            get {
                return ResourceManager.GetString("NumberHealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Participantes:.
        /// </summary>
        public static string NumberParticipants {
            get {
                return ResourceManager.GetString("NumberParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        public static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação para o Organizador.
        /// </summary>
        public static string ObservationToOrganizer {
            get {
                return ResourceManager.GetString("ObservationToOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nossa Agenda.
        /// </summary>
        public static string OurSchedule {
            get {
                return ResourceManager.GetString("OurSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago?.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago.
        /// </summary>
        public static string PaidWithoutAccent {
            get {
                return ResourceManager.GetString("PaidWithoutAccent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participantes.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Churras da Trinca.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Arrecadado.
        /// </summary>
        public static string TotalCollected {
            get {
                return ResourceManager.GetString("TotalCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total a ser Arrecadado:.
        /// </summary>
        public static string TotalToBeCollected {
            get {
                return ResourceManager.GetString("TotalToBeCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Churras da Trinca - Erro.
        /// </summary>
        public static string ViewErrorTitle {
            get {
                return ResourceManager.GetString("ViewErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Evento.
        /// </summary>
        public static string ViewEvent {
            get {
                return ResourceManager.GetString("ViewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Churras da Trinca - Evento.
        /// </summary>
        public static string ViewEventTitle {
            get {
                return ResourceManager.GetString("ViewEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Churras da Trinca - Home.
        /// </summary>
        public static string ViewHomeTitle {
            get {
                return ResourceManager.GetString("ViewHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Participante.
        /// </summary>
        public static string ViewParticipant {
            get {
                return ResourceManager.GetString("ViewParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Churras da Trinca - Participante.
        /// </summary>
        public static string ViewParticipantTitle {
            get {
                return ResourceManager.GetString("ViewParticipantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Churras da Trinca - Agenda.
        /// </summary>
        public static string ViewScheduleTitle {
            get {
                return ResourceManager.GetString("ViewScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quando?.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porquê?.
        /// </summary>
        public static string Why {
            get {
                return ResourceManager.GetString("Why", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com bebida (R$).
        /// </summary>
        public static string WithDrink {
            get {
                return ResourceManager.GetString("WithDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com bebida.
        /// </summary>
        public static string WithDrinkWithoutCurrency {
            get {
                return ResourceManager.GetString("WithDrinkWithoutCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem bebida (R$).
        /// </summary>
        public static string WithoutDrink {
            get {
                return ResourceManager.GetString("WithoutDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem bebida.
        /// </summary>
        public static string WithoutDrinkWithoutCurrency {
            get {
                return ResourceManager.GetString("WithoutDrinkWithoutCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
